---
title: "Statistical Learning 2"
output: html_document
---
1 Simulation Study
1.1 The data generation process


```{r setup, include=FALSE}
library('MASS')
library(plyr)
```


(1)Generate the first 10 coordinates of each µj vector j = 1, ..,3
```{r}

sampling <- NULL
for (i in 1:10) {
first_10 <- rnorm(3,0,1) #mu
sampling <- rbind(sampling,first_10)
}

```

(2) Write a function that outputs a simulated dataset of dimension (100 × p)
```{r}
create_data <- function(sampling, p, sigma_e){
  x_data <- NULL
  if(p >10){
  mu_num <- rep(0,(p - 10))
  mu <- cbind(mu_num, mu_num, mu_num)
  mu <- rbind(sampling,mu)
  mu <- as.data.frame(mu) 
  } else {
    mu <- as.data.frame(sampling)
  }
  d <- diag(sqrt(rep(sigma_e,p)))
  dat_a = mvrnorm(20,mu = mu[,1],Sigma=  d)
  dat_b = mvrnorm(30,mu = mu[,2],Sigma=  d)
  dat_c = mvrnorm(50,mu = mu[,3],Sigma=  d)
  x_data = rbind(dat_a, dat_b,dat_c)
  return(x_data)
}
```

(3)Choose 4 levels of σ^2 and use p = 10, 20, 50.
choosing sigma : 1,2,5,7
4. For each combination of σ^2 and p, generate multiple datasets (say B = 50).
```{r}
sigma_list <- c(1,2,5,7)
p <- c(10,20,50)
simulation <- function(sampling,p,sigma_list,B){
  s_total <- NULL
  for (i in p) {
    for (j in sigma_list) {
      s <- NULL
      s <- replicate( n = B,sampling,simplify = F)
      s <- lapply(s,create_data,p = i,sigma_e = j)
      s_total <- cbind(s_total,s)
    }
  }
  return(s_total)
}

gene <- simulation(sampling,p,sigma_list,50)
```

```{r}


```